### ISSUE TITLE
"__webpack_share_scopes__" is not defined

### ISSUE THREAD

**Issue by lij20** [zhangHongEn/universal-module-federation-plugin#9]
Using this with webpack v4 + server-side rendering and getting `ReferenceError: __webpack_share_scopes__ is not defined` error.

```
function getDefaultShareScopes() {
  return typeof __global_share_scopes__ === "undefined" ? 
    __webpack_share_scopes__ || {} : __global_share_scopes__
}
```

**Comment by zhangHongEn** [comment]
mf-webpack4 + module-federation-runtime ？

**Comment by zhangHongEn** [comment]
this issue is module-federation-runtime ? I'll try to reproduce it later

**Comment by lij20** [comment]
> mf-webpack4 + module-federation-runtime ？

Yes, that's correct.

**Comment by zhangHongEn** [comment]
release fix tomorrow, and then find another time to supplement the SSR code

**Comment by zhangHongEn** [comment]
module-federation-runtime@1.1.9
